opening_title: Different Types of Collections
opening_image: images/consumers.png

closing_title: How Do You Build Collections?
closing_image: images/integrations_postmanaut_4.png

markdown: kramdown
highlighter: rouge
relative_permalinks: false
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""
